clusterName: ${eks_cluster_id}
region: ${aws_region}
image:
  repository: ${repository}

resources:
  limits:
    cpu: 200m
    memory: 256Mi
  requests:
    cpu: 200m
    memory: 256Mi

podDisruptionBudget:
 maxUnavailable: 1
